version = 0.1

[default.deploy.parameters]
stack_name = "linh-byol-go-gin"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
disable_rollback = false
s3_prefix = "linh-byol-go-gin"
image_repositories = []

[default.global.parameters]
region = "us-west-2"
